#测试环境
spring:
  profiles:
    include: mybatis-test

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/coresky?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: Dev&8989
    type: com.alibaba.druid.pool.DruidDataSource
    #数据源其他配置
    initialSize: 5
    minIdle: 5
    maxActive: 10
    maxWait: 60000

  redis:
    host: 127.0.0.1
    port: 6379

web3:
  url: https://goerli.infura.io/v3/e0ec62bcaf8c48f280127c0aa347ca24

#https://testnets-api.opensea.io   /v2/orders/  goerli   /seaport/offers?limit=1
#https://api.opensea.io            /v2/orders/  {chain}   /seaport/offers
opensea:
  api: https://testnets-api.opensea.io
  chain: goerli
  url: wss://testnets-stream.openseabeta.com/socket/websocket