spring:
  main:
    allow-circular-references: true
  profiles:
    active: test

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  task:
    execution:
      pool:
        core-size: 200

  http:
    multipart:
      maxFileSize: 2MB

server:
  port: 28002
  tomcat:
    accept-count: 1000
    max-connections: 10000

mybatis:
  config-location: classpath:mybatis-config.xml

logging:
  level:
    com.project.market.mapper: info
  file:
    name: /mnt/ftp/price-update/logs/price.log